### PR TITLE
small layout changes

### PR DESCRIPTION
**Pull request by ygg2**
- It adds a mild amount of space around/between messages and aligns a few items
- It decreases the size of reply/status text and makes it relative to the default font size
- It removes the overflow on the right side that caused horizontal scrollbar

### CODE REVIEW

**Comment by ygg2** [comment]
- It standardizes some margins and some font sizes and button styles across browsers
- It fixes the reply popup and truncating the server name
- It adds theme properties for code text color, server sidebar color, and shadow color
- It makes the quote lines for multiline quotes fuse
- It changes the style of the scrollbar

**Comment by MathMan05** [comment]
so sorry about this again, but there are merge conflicts

**Comment by ygg2** [comment]
Sorry I didn't see this- fixing now

**Comment by MathMan05** [comment]
shoot, I'm failing to merge this correctly, I'll fix it

**Comment by MathMan05** [comment]
did a close enough and re-did all the changes

**Pull request merged**
