### PR TITLE
Add emoji support & render markdown in embeds

### PR DESCRIPTION
**Pull request by DEVTomatoCake**
Had to remove
```css
width: auto;
height: auto;
```
otherwise `.width` and `.height` don't work for imgs

### CODE REVIEW

**Comment by MathMan05** [comment]
```
title.innerHTML=markdown(this.json.title).innerHTML;
p.innerHTML=markdown(this.json.description).innerHTML;
```
This isn't how you do that, you do it like title.append(markdown(this.json.title));

**Comment by DEVTomatoCake** [comment]
> ```
> title.innerHTML=markdown(this.json.title).innerHTML;
> p.innerHTML=markdown(this.json.description).innerHTML;
> ```
> 
> This isn't how you do that, you do it like title.append(markdown(this.json.title));

That'd cause other styling, and in the case of title, the URL, to get lost, wouldn't it?

**Comment by MathMan05** [comment]
they both do the same thing, though that'll have more overhead, and I think it'd also break spoilers and a few other md things in the future

**Comment by DEVTomatoCake** [comment]
> they both do the same thing

But a `span` element isn't the same as an `a` one?

**Comment by MathMan05** [comment]
that is true, though the span is within the a so it should do the same thing. This still needs to be fixed as spoilers will not work correctly with this setup

**Comment by DEVTomatoCake** [comment]
I just tested it and spoilers work for me
I'll still change it because I originally read it wrong and yea, it makes more sense this way, but it doesn't break anything

**Comment by DEVTomatoCake** [comment]
Actually, no, it doesn't make sense because this adds another HTML depth layer as there's another <span> element present within the other element... Using `innerHTML` this isn't the case
But well

**Comment by MathMan05** [comment]
looks good

**Pull request merged**
