### PR TITLE
[Instance.json] Added Star Chat

### PR DESCRIPTION
**Pull request by LeDeathAmongst**

### CODE REVIEW

**Comment by MathMan05** [comment]
Ok, thanks for the pull, but two things, firstly do you not have a wellknown? Also for the spacebar instance there needs to be an @url so that way people know which instance the account it on

**Comment by LeDeathAmongst** [comment]
No, i don't have a `wellknown`, and for the @url, it would just be the base spacebar url?

**Comment by MathMan05** [comment]
Yeah, the instance URL

**Comment by LeDeathAmongst** [comment]
so, i can do `https://spacebar.prismbot.icu`?

**Comment by MathMan05** [comment]
the rul in the json must only be there if a wellknown exists, otherwise don't include it

**Comment by LeDeathAmongst** [comment]
I don't have a wellknown

**Comment by LeDeathAmongst** [comment]
For some reason, when i do it locally without `url` and `wellknown`, it won't allow any connections

**Comment by MathMan05** [comment]
as I said, no wellknown, no url on the json object

**Comment by LeDeathAmongst** [comment]
image
Without url and wellknown, this is in browser console

**Comment by MathMan05** [comment]
why was this closed?

**Comment by LeDeathAmongst** [comment]
I deleted the repo i opened with it. I was working on fixing a bug and got angry so i deleted it lol

**Comment by MathMan05** [comment]
can you please make a pull with star chat so it can be on the list?

**Pull request closed without merging**
