### PR TITLE
A bunch of changes to make contextmenu.ts more readable

### PR DESCRIPTION
**Pull request by aintDatCap**

### CODE REVIEW

**Comment by MathMan05** [comment]
What's the intent here?

**Comment by aintDatCap** [comment]
> What's the intent here?

It started with a little change in contextmenu.ts, but then i saw that you're keeping the .dist folder in the repository (this can make the fetching process longer than it should be), so i've deleted that folder as well as added a bunch of node command to compile and run the repository

**Comment by MathMan05** [comment]
and it's not that much larger

**Comment by MathMan05** [comment]
If this were to move forward, the node server would need to be fixed to auto compile the TS, and/or compiling before being ran. And @DEVTomatoCake would need to be on board

**Comment by MathMan05** [comment]
though some of the other changes might be accepted removing ./.dist at this point isn't possible without other solutions

**Comment by aintDatCap** [comment]
ok, lemme revise the pull request

**Comment by aintDatCap** [comment]
Now it should be fixed

**Review by DEVTomatoCake — APPROVED** [review]
neat
Maybe add a watch script too? there's the `-w` argument for tsc iirc

**Comment by MathMan05** [comment]
I'm going to have to close this, it's not correct anymore.

**Pull request closed without merging**
